version: '3.7'
services:
  familytree:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - familytree_storage:/app/storage
    tmpfs:
      - /tmp/pids/
    environment:
      - PIDFILE=/tmp/pids/server.pid
      - RAILS_ENV=production
      - FAMILYTREE_DEPLOY=local
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - S3_BUCKET_NAME

volumes:
  familytree_storage:
    external: false
